return {
	Title = "安居乐业生育办",
	Version = "1.0.0.0",
	GameVersion = "0.0.70.69",
	BackendPlugins = {
		[1] = "HappyLife.dll",
		[2] = "HappyLifeEvent.dll",
	},
	FrontendPlugins = {
		[1] = "HappyLife.Frontend.dll",
	},
	Author = "kkle1994@outlook.com",
	Description = "优生优育，拒绝蛐蛐。反馈bug还是去贴吧。p/8054902346 (傻逼Steam不让放连接)，或者可以加qq群：657760393。此项目已经开源于：https://github.com/kkle1994/HappyLife",
	Cover = "Cover.jpg",
	Source = 0,
	FileId = 2871634952,
	TagList = {
		[1] = "Extensions",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "BanCricketBorn",
			DisplayName = "不生蛐蛐",
			Description = "永不生育蛐蛐。",
			DefaultValue = false,
		},
		[2] = {
			SettingType = "Slider",
			Key = "TaiwuRecoverPercent",
			DisplayName = "太吾回血百分比",
			Description = "太吾战斗回血速度。",
			MinValue = 0,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[3] = {
			SettingType = "Slider",
			Key = "EnemyRecoverPercent",
			DisplayName = "敌人回血百分比",
			Description = "敌人战斗回血速度。",
			MinValue = 0,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[4] = {
			SettingType = "Slider",
			Key = "WeaponDurabilityRate",
			DisplayName = "武器消耗概率",
			Description = "武器消耗耐久的概率，从1%到100%，0%为完全不消耗。",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 100,
		},
		[5] = {
			SettingType = "Slider",
			Key = "IncreaseBuildingMaxCount",
			DisplayName = "增加建筑上限",
			Description = "增加太吾村可以建设的建筑物数量上限。",
			MinValue = 0,
			MaxValue = 200,
			StepSize = 1,
			DefaultValue = 0,
		},
		[6] = {
			SettingType = "Slider",
			Key = "FavorabilityMultiple",
			DisplayName = "好感提升倍数",
			Description = "增加所有人之间的好感度提升速度。（有爱的世界）",
			MinValue = 1,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 1,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "UnlimitedInformation",
			DisplayName = "无限消息次数",
			Description = "无限次使用消息。",
			DefaultValue = false,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "BanTaiwuInfected",
			DisplayName = "禁止太吾入魔",
			Description = "禁止太吾入魔。",
			DefaultValue = false,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "BanTaiwuVillagerInfected",
			DisplayName = "禁止村民入魔",
			Description = "禁止太吾村村民入魔。",
			DefaultValue = false,
		},
		[10] = {
			SettingType = "Slider",
			Key = "InfectedSpeedRate",
			DisplayName = "世界入魔速度",
			Description = "全世界的入魔速度。100%为原速度，越高越快，甚至可以反向减少入魔值（但无法反转已入魔的人）。",
			MinValue = -100,
			MaxValue = 500,
			StepSize = 1,
			DefaultValue = 100,
		},
		[11] = {
			SettingType = "Slider",
			Key = "AddResourceMultiple",
			DisplayName = "资源获取倍率",
			Description = "太吾的资源获取倍率。",
			MinValue = 1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 1,
		},
		[12] = {
			SettingType = "Toggle",
			Key = "ResourceMultipleOnlyForMonthlyIncreasing",
			DisplayName = "仅影响当月资源",
			Description = "太吾资源获取倍率仅对当月资源有效。",
			DefaultValue = true,
		},
		[13] = {
			SettingType = "Toggle",
			Key = "UnlimitedMerchantFavorability",
			DisplayName = "商人好感最大",
			Description = "商人的好感直接设为6000。",
			DefaultValue = false,
		},
		[14] = {
			SettingType = "Toggle",
			Key = "HighLevelShop",
			DisplayName = "解锁高级商品",
			Description = "卖高级商品。",
			DefaultValue = false,
		},
		[15] = {
			SettingType = "Slider",
			Key = "MaxSaveBackupCount",
			DisplayName = "存档备份数量",
			Description = "最大存档备份数量，-1为关闭。别问我什么最大只有127，因为存档数量用的是sbyte。",
			MinValue = -1,
			MaxValue = 127,
			StepSize = 1,
			DefaultValue = 3,
		},
		[16] = {
			SettingType = "Toggle",
			Key = "TaiwuValligerNoQiDisorder",
			DisplayName = "村民无紊乱",
			Description = "将村民的气息紊乱回复提升。",
			DefaultValue = false,
		},
		[17] = {
			SettingType = "Toggle",
			Key = "UnlimitApprovingRateUpperLimit",
			DisplayName = "解锁门派支持",
			Description = "门派支持度。",
			DefaultValue = false,
		},
		[18] = {
			SettingType = "Toggle",
			Key = "VillagersNeverDie",
			DisplayName = "村民不掉健康",
			Description = "村民不会掉健康值。",
			DefaultValue = false,
		},
		[19] = {
			SettingType = "Toggle",
			Key = "TaiwuNeverDie",
			DisplayName = "太吾不掉健康",
			Description = "太吾不会掉健康值。",
			DefaultValue = false,
		},
		[20] = {
			SettingType = "Toggle",
			Key = "SameConsummateLevel",
			DisplayName = "全世界同精纯",
			Description = "全世界精纯境界水平一样。",
			DefaultValue = false,
		},
		[21] = {
			SettingType = "Slider",
			Key = "SameConsummateLevelValue",
			DisplayName = "世界精纯水平",
			Description = "全世界精纯境界水平，须先开启“全世界同精纯”。",
			MinValue = 0,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 0,
		},
		[22] = {
			SettingType = "Toggle",
			Key = "TaiwuMustPregnant",
			DisplayName = "太吾必怀孕",
			Description = "开启后太吾或其配偶每次交媾必定怀孕。",
			DefaultValue = false,
		},
		[23] = {
			SettingType = "Toggle",
			Key = "NoTaiwuPregnancyLock",
			DisplayName = "太吾无怀孕CD",
			Description = "太吾无怀孕CD。",
			DefaultValue = false,
		},
		[24] = {
			SettingType = "Toggle",
			Key = "TaiwuFertilityMax",
			DisplayName = "太吾生育力Max",
			Description = "开启后太吾的每月交媾次数提升。",
			DefaultValue = false,
		},
		[25] = {
			SettingType = "Slider",
			Key = "TaiwuChildrenLimit",
			DisplayName = "太吾子女上限",
			Description = "太吾的子女上限，-1为原游戏上限。（会限制必怀孕的功能）",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[26] = {
			SettingType = "Slider",
			Key = "TaiwuSpouseChildrenLimit",
			DisplayName = "太吾配偶子女上限",
			Description = "太吾每个配偶的子女上限，-1为原游戏上限。（会限制必怀孕的功能）",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[27] = {
			SettingType = "Slider",
			Key = "NpcChildrenLimit",
			DisplayName = "NPC子女上限",
			Description = "NPC的子女上限，-1为原游戏上限。不包括和太吾生孩子。",
			MinValue = -1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = -1,
		},
		[28] = {
			SettingType = "Toggle",
			Key = "ShopTaiwuAgeIncreasing",
			DisplayName = "停止太吾年龄增长",
			Description = "停止太吾年龄增长",
			DefaultValue = false,
		},
		[29] = {
			SettingType = "Toggle",
			Key = "UnlimitedGroupMemberCount",
			DisplayName = "无限同道数量",
			Description = "无限同道数量",
			DefaultValue = false,
		},
		[30] = {
			SettingType = "Toggle",
			Key = "UnlimitedSworn",
			DisplayName = "无限结义人数",
			Description = "无限结义人数。",
			DefaultValue = false,
		},
		[31] = {
			SettingType = "Toggle",
			Key = "UnlimitedMarry",
			DisplayName = "无限配偶人数",
			Description = "不限制你的配偶人数。",
			DefaultValue = false,
		},
		[32] = {
			SettingType = "Toggle",
			Key = "UnlimitedConfess",
			DisplayName = "可向任何人表白",
			Description = "可向任何人表白",
			DefaultValue = false,
		},
		[33] = {
			SettingType = "Toggle",
			Key = "ShowKidCharm",
			DisplayName = "显示儿童魅力",
			Description = "显示儿童魅力。",
			DefaultValue = false,
		},
		[34] = {
			SettingType = "Toggle",
			Key = "ShowMaskCharm",
			DisplayName = "显示遮面魅力",
			Description = "显示遮面魅力（界青衣服等）。",
			DefaultValue = false,
		},
		[35] = {
			SettingType = "Toggle",
			Key = "EnableBuildResource",
			DisplayName = "建造资源(需重启)",
			Description = "允许建造自然资源(重启生效)。",
			DefaultValue = false,
		},
		[36] = {
			SettingType = "Toggle",
			Key = "NoDependentBuilding",
			DisplayName = "无视附属(需重启)",
			Description = "建造无视附属建筑，需先开启允许建造资源！(重启生效)",
			DefaultValue = false,
		},
		[37] = {
			SettingType = "Toggle",
			Key = "FixConfessIssue",
			DisplayName = "修复表白公式",
			Description = "解除同性限制、解决太吾子女或配偶带来的减益。",
			DefaultValue = false,
		},
		[38] = {
			SettingType = "Toggle",
			Key = "AllowTaiwuHomoPregnant",
			DisplayName = "太吾同性怀孕",
			Description = "允许太吾同性怀孕。",
			DefaultValue = false,
		},
		[39] = {
			SettingType = "Dropdown",
			Key = "TaiwuHomoPregnant",
			DisplayName = "同性交媾怀孕方",
			Description = "开启后太吾或其配偶每次交媾必定怀孕。",
			Options = {
				[1] = "随机",
				[2] = "太吾",
				[3] = "对方",
			},
			DefaultValue = 0,
		},
		[40] = {
			SettingType = "Toggle",
			Key = "BanNTRTaiwu",
			DisplayName = "彻底防止NTR太吾",
			Description = "所有NPC向和太吾有爱慕关系的人表白必定失败，反之亦然。",
			DefaultValue = false,
		},
		[41] = {
			SettingType = "Toggle",
			Key = "HideKillRuMoRenOption",
			DisplayName = "隐藏杀相枢选项",
			Description = "隐藏和入魔人对战失败逃走时，杀相枢的选项。",
			DefaultValue = false,
		},
		[42] = {
			SettingType = "Toggle",
			Key = "BabyKickable",
			DisplayName = "可以踢出婴儿",
			Description = "可以将你的宝宝踢出队伍。",
			DefaultValue = false,
		},
		[43] = {
			SettingType = "Toggle",
			Key = "FightForMarryWithMarried",
			DisplayName = "事件无视已婚",
			Description = "比武招亲等事件无视已婚。",
			DefaultValue = false,
		},
		[44] = {
			SettingType = "Toggle",
			Key = "KeepVirgin",
			DisplayName = "保持童贞",
			Description = "交媾不会影响童贞，止乎于礼。甚至会修复童贞（采阳补阴）。",
			DefaultValue = false,
		},
		[45] = {
			SettingType = "Dropdown",
			Key = "CombatDiffcultyOverwrite",
			DisplayName = "覆盖战斗难度",
			Description = "覆盖你原有存档的战斗难度（不会修改存档数据）。",
			Options = {
				[1] = "关闭",
				[2] = "简单",
				[3] = "正常",
				[4] = "困难",
				[5] = "极难",
			},
			DefaultValue = 0,
		},
		[46] = {
			SettingType = "Toggle",
			Key = "CancelMonthlyEventFavorReduce",
			DisplayName = "取消过月降好感",
			Description = "将过月事件中的琴棋书画以及秘闻导致的好感下降设为0。",
			DefaultValue = false,
		},
		[47] = {
			SettingType = "Toggle",
			Key = "CancelMonthlyEventHappinessReduce",
			DisplayName = "取消过月降心情",
			Description = "将过月事件中的太吾的妻妾（包括未婚）心情降低。",
			DefaultValue = false,
		},
		[48] = {
			SettingType = "Toggle",
			Key = "NoImmoralFameActions",
			DisplayName = "无不道德声誉",
			Description = "删除欺凌幼小、伤风败俗、罔顾人伦、结交声誉低的情侣导致的声誉下降。",
			DefaultValue = false,
		},
		[49] = {
			SettingType = "Toggle",
			Key = "BanEventSpendPrestige",
			DisplayName = "无消耗恩义事件",
			Description = "删除商会赞誉和推恩施义的过月事件。",
			DefaultValue = false,
		},
		[50] = {
			SettingType = "Toggle",
			Key = "EnemyNestDefaultIncome",
			DisplayName = "巢穴有默认收益",
			Description = "未实装的巢穴有默认的声望收益，为1000-2000。且随机数拟合后符合正态分布。",
			DefaultValue = false,
		},
		[51] = {
			SettingType = "Toggle",
			Key = "AllowSetUpAnyTeammate",
			DisplayName = "允许任意做媒",
			Description = "男媒女妁支持给任何人（甚至是你老婆）介绍任何可用的队友（甚至是你老婆）。",
			DefaultValue = false,
		},
		[52] = {
			SettingType = "Slider",
			Key = "ImproveSkillWithWorkPossibility",
			DisplayName = "工作提升技能概率",
			Description = "工作会提升技能资质，每个月都有一定概率提升，概率为你设置的值。如果为镖局等则会随机提升一项战斗技能的资质。",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 0,
		},
		[53] = {
			SettingType = "Slider",
			Key = "ImproveSkillWithWorkLimited",
			DisplayName = "工作提升技能上限",
			Description = "工作会提升技能资质的上限。",
			MinValue = 50,
			MaxValue = 200,
			StepSize = 1,
			DefaultValue = 90,
		},
		[54] = {
			SettingType = "Dropdown",
			Key = "WorldCreatePeopleSex",
			DisplayName = "世界初始性别",
			Description = "覆盖新的世界上所有人的初始性别。",
			Options = {
				[1] = "随机",
				[2] = "男",
				[3] = "女",
			},
			DefaultValue = 0,
		},
		[55] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultSex",
			DisplayName = "村民招募性别",
			Description = "覆盖你所有招募建筑的招募性别。",
			Options = {
				[1] = "随机",
				[2] = "男",
				[3] = "女",
			},
			DefaultValue = 0,
		},
		[56] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultAppearanceLowerLimit",
			DisplayName = "村民招募外貌下限",
			Description = "村民招募外貌的下限。",
			Options = {
				[1] = "随机",
				[2] = "寻常",
				[3] = "出众",
				[4] = "瑾瑜",
				[5] = "凤仪",
				[6] = "出尘",
				[7] = "天人",
			},
			DefaultValue = 0,
		},
		[57] = {
			SettingType = "Dropdown",
			Key = "VillagerRecrultMorality",
			DisplayName = "村民招募立场",
			Description = "村民招募的默认立场。",
			Options = {
				[1] = "随机",
				[2] = "唯我",
				[3] = "叛逆",
				[4] = "中庸",
				[5] = "仁善",
				[6] = "刚正",
			},
			DefaultValue = 0,
		},
		[58] = {
			SettingType = "Toggle",
			Key = "UnlimitedReferenceBookSlot",
			DisplayName = "解锁参考书栏位",
			Description = "解锁参考书栏位。",
			DefaultValue = false,
		},
		[59] = {
			SettingType = "Dropdown",
			Key = "TaiwuChildGender",
			DisplayName = "太吾子女性别",
			Description = "太吾子女性别。",
			Options = {
				[1] = "随机",
				[2] = "男",
				[3] = "女",
			},
			DefaultValue = 0,
		},
		[60] = {
			SettingType = "Dropdown",
			Key = "WorldChildGender",
			DisplayName = "其他人子女性别",
			Description = "其他人子女性别。",
			Options = {
				[1] = "随机",
				[2] = "男",
				[3] = "女",
			},
			DefaultValue = 0,
		},
		[61] = {
			SettingType = "Toggle",
			Key = "RestoreAttainmentPerGrade",
			DisplayName = "提高造诣加成",
			Description = "恢复造诣加成上限到270%。",
			DefaultValue = false,
		},
		[62] = {
			SettingType = "Slider",
			Key = "TaiwuChildQuickGrowAge",
			DisplayName = "村中快速长到X岁",
			Description = "太吾村中，孩童会每个月长大一岁直到X岁，设为0则无效。",
			MinValue = 0,
			MaxValue = 14,
			StepSize = 1,
			DefaultValue = 0,
		},
		[63] = {
			SettingType = "Slider",
			Key = "OtherChildQuickGrowAge",
			DisplayName = "村外快速长到X岁",
			Description = "太吾村外，孩童会每个月长大一岁直到X岁，设为0则无效。",
			MinValue = 0,
			MaxValue = 14,
			StepSize = 1,
			DefaultValue = 0,
		},
		[64] = {
			SettingType = "Toggle",
			Key = "OnlyExistBloodParents",
			DisplayName = "父母栏有亲生父母",
			Description = "父母栏里一定有亲生父母。（仅对太吾子女有效）",
			DefaultValue = false,
		},
		[65] = {
			SettingType = "Toggle",
			Key = "BanAddStepChildren",
			DisplayName = "禁止过继子女",
			Description = "禁止过继子女，仅对太吾有效。",
			DefaultValue = false,
		},
		[66] = {
			SettingType = "Toggle",
			Key = "GrowAbilitiesWithLoopingNeigong",
			DisplayName = "运转内功加属性",
			Description = "可以通过运转光明狮子劲、损悦法等内功提升属性（是左下角的运转不是配了就行），每个月增加1点。",
			DefaultValue = false,
		},
		[67] = {
			SettingType = "Toggle",
			Key = "GrowQualificationsWithReadingBook",
			DisplayName = "读九品书加资质",
			Description = "阅读九品书可以增加对应的资质，每个月增加1点。",
			DefaultValue = false,
		},
		[68] = {
			SettingType = "Toggle",
			Key = "AllowAllGenderInOrganization",
			DisplayName = "门派可有所有性别",
			Description = "任何门派都可以有男有女，不影响晋升",
			DefaultValue = false,
		},
		[69] = {
			SettingType = "Toggle",
			Key = "LockDaysInMonth",
			DisplayName = "锁定时间",
			Description = "开启后时间只会因为主动消耗而降低。",
			DefaultValue = false,
		},
		[70] = {
			SettingType = "Toggle",
			Key = "MarryAdventrueIgnoreMarried",
			DisplayName = "结婚奇遇无视已婚",
			Description = "结婚奇遇无视已婚。",
			DefaultValue = false,
		},
		[71] = {
			SettingType = "Toggle",
			Key = "BanFavorDebt",
			DisplayName = "禁止欠恩施义",
			Description = "禁止产生新的欠恩施义，已经有的没办法消除。",
			DefaultValue = false,
		},
		[72] = {
			SettingType = "Toggle",
			Key = "RemoveSupportCost",
			DisplayName = "取消部分支持花费",
			Description = "消除本地恩义和历练的花费，但是依然需要达到要求。",
			DefaultValue = false,
		},
		[73] = {
			SettingType = "Toggle",
			Key = "SeverAndDivorce",
			DisplayName = "背恩绝情离婚",
			Description = "背恩绝情，顺便离婚（如果结了的话）。",
			DefaultValue = false,
		},
		[74] = {
			SettingType = "Toggle",
			Key = "MakeItemImmediately",
			DisplayName = "立马完成物品制作",
			Description = "快速制作物品。",
			DefaultValue = false,
		},
	},
	WorkshopCover = "Cover.jpg",
	Visibility = 0,
	UpdateLogList = {
		[1] = {
			Timestamp = 1714768798,
			LogList = {
				[1] = "修复太污村民模板失效的问题，修复建筑资源失效的问题（已知问题：村民招募和实际长相、力场不同，但是筛选可生效）",
			},
		},
	},
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
}
