return {
	Title = "安居乐业生育办",
	Version = "1.0",
	BackendPlugins = {"HappyLife.dll", "HappyLifeEvent.dll"},
	FrontendPlugins = {"HappyLife.Frontend.dll"},
	Author = "kkle1994@outlook.com",
	Description = "优生优育，拒绝蛐蛐。反馈bug还是去贴吧。p/8054902346 (傻逼Steam不让放连接)，或者可以加qq群：657760393",
	Cover = "Cover.jpg",
	Source = 1,
	FileId = 2871634952,
	TagList = {"Extensions"},
	DefaultSettings = {
		{Key="BanCricketBorn", DisplayName="不生蛐蛐", Description="永不生育蛐蛐。", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuRecoverPercent", DisplayName="太吾回血百分比", Description="太吾战斗回血速度。", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=500},
		{Key="EnemyRecoverPercent", DisplayName="敌人回血百分比", Description="敌人战斗回血速度。", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=500},
		{Key="WeaponDurabilityRate", DisplayName="武器消耗概率", Description="武器消耗耐久的概率，从1%到100%，0%为完全不消耗。", SettingType="Slider", DefaultValue=100, MinValue=0, MaxValue=100},
		{Key="IncreaseBuildingMaxCount", DisplayName="增加建筑上限", Description="增加太吾村可以建设的建筑物数量上限。", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=200},
		{Key="FavorabilityMultiple", DisplayName="好感提升倍数", Description="增加所有人之间的好感度提升速度。（有爱的世界）", SettingType="Slider", DefaultValue=1, MinValue=1, MaxValue=100},
		{Key="UnlimitedInformation", DisplayName="无限消息次数", Description="无限次使用消息。", SettingType="Toggle", DefaultValue=false},
		{Key="BanTaiwuInfected", DisplayName="禁止太吾入魔", Description="禁止太吾入魔。", SettingType="Toggle", DefaultValue=false},
		{Key="BanTaiwuVillagerInfected", DisplayName="禁止村民入魔", Description="禁止太吾村村民入魔。", SettingType="Toggle", DefaultValue=false},
		{Key="InfectedSpeedRate", DisplayName="世界入魔速度", Description="全世界的入魔速度。100%为原速度，越高越快，甚至可以反向减少入魔值（但无法反转已入魔的人）。", SettingType="Slider", DefaultValue=100, MinValue=-100, MaxValue=500},
		{Key="AddResourceMultiple", DisplayName="资源获取倍率", Description="太吾的资源获取倍率。", SettingType="Slider", DefaultValue=1, MinValue=1, MaxValue=20},
		{Key="ResourceMultipleOnlyForMonthlyIncreasing", DisplayName="仅影响当月资源", Description="太吾资源获取倍率仅对当月资源有效。", SettingType="Toggle", DefaultValue=true},
		{Key="UnlimitedMerchantFavorability", DisplayName="商人好感最大", Description="商人的好感直接设为6000。", SettingType="Toggle", DefaultValue=false},
		{Key="HighLevelShop", DisplayName="解锁高级商品", Description="卖高级商品。", SettingType="Toggle", DefaultValue=false},
		{Key="MaxSaveBackupCount", DisplayName="存档备份数量", Description="最大存档备份数量，-1为关闭。别问我什么最大只有127，因为存档数量用的是sbyte。", SettingType="Slider", DefaultValue=3, MinValue=-1, MaxValue=127},
		{Key="TaiwuValligerNoQiDisorder", DisplayName="村民无紊乱", Description="将村民的气息紊乱回复提升。", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitApprovingRateUpperLimit", DisplayName="解锁门派支持", Description="门派支持度。", SettingType="Toggle", DefaultValue=false},
		{Key="VillagersNeverDie", DisplayName="村民不掉健康", Description="村民不会掉健康值。", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuNeverDie", DisplayName="太吾不掉健康", Description="太吾不会掉健康值。", SettingType="Toggle", DefaultValue=false},
		{Key="SameConsummateLevel", DisplayName="全世界同精纯", Description="全世界精纯境界水平一样。", SettingType="Toggle", DefaultValue=false},
		{Key="SameConsummateLevelValue", DisplayName="世界精纯水平", Description="全世界精纯境界水平，须先开启“全世界同精纯”。", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=20},
		{Key="TaiwuMustPregnant", DisplayName="太吾必怀孕", Description="开启后太吾或其配偶每次交媾必定怀孕。", SettingType="Toggle", DefaultValue=false},
		{Key="NoTaiwuPregnancyLock", DisplayName="太吾无怀孕CD", Description="太吾无怀孕CD。", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuFertilityMax", DisplayName="太吾生育力Max", Description="开启后太吾的每月交媾次数提升。", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuChildrenLimit", DisplayName="太吾子女上限", Description="太吾的子女上限，-1为原游戏上限。（会限制必怀孕的功能）", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="TaiwuSpouseChildrenLimit", DisplayName="太吾配偶子女上限", Description="太吾每个配偶的子女上限，-1为原游戏上限。（会限制必怀孕的功能）", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="NpcChildrenLimit", DisplayName="NPC子女上限", Description="NPC的子女上限，-1为原游戏上限。不包括和太吾生孩子。", SettingType="Slider", DefaultValue=-1, MinValue=-1, MaxValue=20},
		{Key="ShopTaiwuAgeIncreasing", DisplayName="停止太吾年龄增长", Description="停止太吾年龄增长", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedGroupMemberCount", DisplayName="无限同道数量", Description="无限同道数量", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedSworn", DisplayName="无限结义人数", Description="无限结义人数。", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedMarry", DisplayName="无限配偶人数", Description="不限制你的配偶人数。", SettingType="Toggle", DefaultValue=false},
		{Key="UnlimitedConfess", DisplayName="可向任何人表白", Description="可向任何人表白", SettingType="Toggle", DefaultValue=false},
		{Key="ShowKidCharm", DisplayName="显示儿童魅力", Description="显示儿童魅力。", SettingType="Toggle", DefaultValue=false},
		{Key="ShowMaskCharm", DisplayName="显示遮面魅力", Description="显示遮面魅力（界青衣服等）。", SettingType="Toggle", DefaultValue=false},
		{Key="EnableBuildResource", DisplayName="建造资源(需重启)", Description="允许建造自然资源(重启生效)。", SettingType="Toggle", DefaultValue=false},
		{Key="NoDependentBuilding", DisplayName="无视附属(需重启)", Description="建造无视附属建筑，需先开启允许建造资源！(重启生效)", SettingType="Toggle", DefaultValue=false},
		{Key="FixConfessIssue", DisplayName="修复表白公式", Description="解除同性限制、解决太吾子女或配偶带来的减益。", SettingType="Toggle", DefaultValue=false},
		{Key="AllowTaiwuHomoPregnant", DisplayName="太吾同性怀孕", Description="允许太吾同性怀孕。", SettingType="Toggle", DefaultValue=false},
		{Key="TaiwuHomoPregnant", DisplayName="同性交媾怀孕方", Description="开启后太吾或其配偶每次交媾必定怀孕。", SettingType="Dropdown", Options={ "随机", "太吾", "对方"}, DefaultValue=0},
		{Key="BanNTRTaiwu", DisplayName="彻底防止NTR太吾", Description="所有NPC向和太吾有爱慕关系的人表白必定失败，反之亦然。", SettingType="Toggle", DefaultValue=false},
		{Key="HideKillRuMoRenOption", DisplayName="隐藏杀相枢选项", Description="隐藏和入魔人对战失败逃走时，杀相枢的选项。", SettingType="Toggle", DefaultValue=false},
		{Key="BabyKickable", DisplayName="可以踢出婴儿", Description="可以将你的宝宝踢出队伍。", SettingType="Toggle", DefaultValue=false},
		{Key="FightForMarryWithMarried", DisplayName="事件无视已婚", Description="比武招亲等事件无视已婚。", SettingType="Toggle", DefaultValue=false},
		{Key="KeepVirgin", DisplayName="保持童贞", Description="交媾不会影响童贞，止乎于礼。甚至会修复童贞（采阳补阴）。", SettingType="Toggle", DefaultValue=false},
		{Key="CombatDiffcultyOverwrite", DisplayName="覆盖战斗难度", Description="覆盖你原有存档的战斗难度（不会修改存档数据）。", SettingType="Dropdown", Options={ "关闭", "简单", "正常","困难", "极难" }, DefaultValue=0},
		{Key="CancelMonthlyEventFavorReduce", DisplayName="取消过月降好感", Description="将过月事件中的琴棋书画以及秘闻导致的好感下降设为0。", SettingType="Toggle", DefaultValue=false},
		{Key="CancelMonthlyEventHappinessReduce", DisplayName="取消过月降心情", Description="将过月事件中的太吾的妻妾（包括未婚）心情降低。", SettingType="Toggle", DefaultValue=false},
		{Key="NoImmoralFameActions", DisplayName="无不道德声誉", Description="删除欺凌幼小、伤风败俗、罔顾人伦、结交声誉低的情侣导致的声誉下降。", SettingType="Toggle", DefaultValue=false},
		{Key="BanEventSpendPrestige", DisplayName="无消耗恩义事件", Description="删除商会赞誉和推恩施义的过月事件。", SettingType="Toggle", DefaultValue=false},
		{Key="EnemyNestDefaultIncome", DisplayName="巢穴有默认收益", Description="未实装的巢穴有默认的声望收益，为1000-2000。且随机数拟合后符合正态分布。", SettingType="Toggle", DefaultValue=false},
		{Key="AllowSetUpAnyTeammate", DisplayName="允许任意做媒", Description="男媒女妁支持给任何人（甚至是你老婆）介绍任何可用的队友（甚至是你老婆）。", SettingType="Toggle", DefaultValue=false},
		{Key="ImproveSkillWithWorkPossibility", DisplayName="工作提升技能概率", Description="工作会提升技能资质，每个月都有一定概率提升，概率为你设置的值。如果为镖局等则会随机提升一项战斗技能的资质。", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=100},
		{Key="ImproveSkillWithWorkLimited", DisplayName="工作提升技能上限", Description="工作会提升技能资质的上限。", SettingType="Slider", DefaultValue=90, MinValue=50, MaxValue=200},
		{Key="WorldCreatePeopleSex", DisplayName="世界初始性别", Description="覆盖新的世界上所有人的初始性别。", SettingType="Dropdown", Options={ "随机", "男", "女"}, DefaultValue=0},
		{Key="VillagerRecrultSex", DisplayName="村民招募性别", Description="覆盖你所有招募建筑的招募性别。", SettingType="Dropdown", Options={ "随机", "男", "女"}, DefaultValue=0},
		{Key="VillagerRecrultAppearanceLowerLimit", DisplayName="村民招募外貌下限", Description="村民招募外貌的下限。", SettingType="Dropdown", Options={ "随机", "寻常", "出众", "瑾瑜", "凤仪", "出尘", "天人" }, DefaultValue=0},
		{Key="VillagerRecrultMorality", DisplayName="村民招募立场", Description="村民招募的默认立场。", SettingType="Dropdown", Options={ "随机", "唯我", "叛逆", "中庸", "仁善", "刚正"}, DefaultValue=0},
		{Key="UnlimitedReferenceBookSlot", DisplayName="解锁参考书栏位", Description="解锁参考书栏位。", SettingType="Toggle", DefaultValue=false},

		{Key="TaiwuChildGender", DisplayName="太吾子女性别", Description="太吾子女性别。", SettingType="Dropdown", Options={ "随机", "男", "女"}, DefaultValue=0},
		{Key="WorldChildGender", DisplayName="其他人子女性别", Description="其他人子女性别。", SettingType="Dropdown", Options={ "随机", "男", "女"}, DefaultValue=0},
		{Key="RestoreAttainmentPerGrade", DisplayName="提高造诣加成", Description="恢复造诣加成上限到270%。", SettingType="Toggle", DefaultValue=false},
		{Key="ChildQuickGrowAge", DisplayName="快速长大到X岁", Description="孩童会每个月长大一岁直到X岁，设为0则无效。", SettingType="Slider", DefaultValue=0, MinValue=0, MaxValue=14},
		{Key="OnlyExistBloodParents", DisplayName="父母栏有亲生父母", Description="父母栏里一定有亲生父母。（仅对太吾子女有效）", SettingType="Toggle", DefaultValue=false},
		{Key="BanAddStepChildren", DisplayName="禁止过继子女", Description="禁止过继子女，仅对太吾有效。", SettingType="Toggle", DefaultValue=false},
		{Key="GrowAbilitiesWithLoopingNeigong", DisplayName="运转内功加属性", Description="可以通过运转光明狮子劲、损悦法等内功提升属性（是左下角的运转不是配了就行），每个月增加1点。", SettingType="Toggle", DefaultValue=false},
		{Key="GrowQualificationsWithReadingBook", DisplayName="读九品书加资质", Description="阅读九品书可以增加对应的资质，每个月增加1点。", SettingType="Toggle", DefaultValue=false},
		{Key="AllowAllGenderInOrganization", DisplayName="门派可有所有性别", Description="任何门派都可以有男有女，不影响晋升", SettingType="Toggle", DefaultValue=false},
		{Key="LockDaysInMonth", DisplayName="锁定时间", Description="开启后时间只会因为主动消耗而降低。", SettingType="Toggle", DefaultValue=false},
		{Key="MarryAdventrueIgnoreMarried", DisplayName="结婚奇遇无视已婚", Description="结婚奇遇无视已婚。", SettingType="Toggle", DefaultValue=false},
		{Key="BanFavorDebt", DisplayName="禁止欠恩施义", Description="禁止产生新的欠恩施义，已经有的没办法消除。", SettingType="Toggle", DefaultValue=false},
		{Key="RemoveSupportCost", DisplayName="取消部分支持花费", Description="消除本地恩义和历练的花费，但是依然需要达到要求。", SettingType="Toggle", DefaultValue=false},
		{Key="SeverAndDivorce", DisplayName="背恩绝情离婚", Description="背恩绝情，顺便离婚（如果结了的话）。", SettingType="Toggle", DefaultValue=false},
		{Key="MakeItemImmediately", DisplayName="立马完成物品制作", Description="快速制作物品。", SettingType="Toggle", DefaultValue=false},
		
	}
}